import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { SignalIllustration } from '@/components/signals/signal-illustration'
import { getSignalById, getSignalsByEntity } from '@/modules/signals/queries'
import { getEventsBySignal } from '@/modules/events/queries'
import { getEvidenceForSignal } from '@/modules/observations/queries'
import { getEntityById } from '@/modules/entities/queries'
import { formatDate, formatRelativeTime, formatCategory } from '@/lib/utils/format'

export const dynamic = 'force-dynamic'

interface SignalPageProps {
  params: Promise<{ slug: string }>
}

const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i

export function isValidSignalSlug(slug: string): boolean {
  return UUID_PATTERN.test(slug)
}

// Pre-generate paths for known signals at build time
export async function generateStaticParams(): Promise<{ slug: string }[]> {
  return []
}

export async function generateMetadata({ params }: SignalPageProps): Promise<Metadata> {
  const { slug } = await params
  if (!isValidSignalSlug(slug)) return { title: 'Signal Not Found' }
  const signal = await getSignalById(slug)
  if (!signal) return { title: 'Signal Not Found' }
  return {
    title: signal.title,
    description: signal.description,
  }
}

/**
 * AIscentra — vfinal /signals/[slug] page (Frontend Design Foundation,
 * layer 5A)
 *
 * Visual language migrated to vfinal (VfinalPublicShell, mint-signal/
 * frost/silver-haze tokens, font-caption/font-heading classes); ALL
 * real functional logic UNCHANGED: getSignalById, getEventsBySignal
 * (same RLS-bound fetch ordering, same safety boundary),
 * SignalIllustration (a real, native SVG generated by this project's
 * own illustration-style.ts -- not an external/temporary image URL, so
 * it stays as-is), notFound() behavior, generateMetadata,
 * generateStaticParams, dynamic rendering. ScoreBar/badge components
 * replaced with plain vfinal-styled bars/pills showing the exact same
 * real numeric values -- no data changed.
 *
 * REAL DATA GAPS CLOSED (explicit owner instruction, 2026-09-05,
 * grounded in a real audit of this project's own database schema
 * before writing any code -- every field below already existed,
 * simply was never queried or displayed here):
 * - getSourceLinksForSignal -> getEvidenceForSignal: same real safety
 *   filtering, now also selects Source.type, Observation.published_at,
 *   and a real excerpt of Observation.content (the actual evidence
 *   text) -- fields that were always in the schema.
 * - getEntityById: the real entity NAME, replacing a bare count.
 * - Signal.evidence_tier: already computed by the real pipeline
 *   (UNASSESSED / PRIMARY_CONFIRMED / CORROBORATED / VERIFIED), never
 *   surfaced in this UI until now.
 * - getSignalsByEntity: an already-existing, already safety-gated
 *   query (has_verified_source + ACTIVE), simply never called from
 *   this page -- powers a real "related signals" list for the same
 *   entity, excluding the current signal itself.
 */
export default async function SignalPage({ params }: SignalPageProps): Promise<React.JSX.Element> {
  const { slug } = await params
  if (!isValidSignalSlug(slug)) notFound()
  const [signal, relatedEvents] = await Promise.all([getSignalById(slug), getEventsBySignal(slug)])

  if (!signal) notFound()

  const firstEntityId = signal.entity_ids[0]
  const [evidence, entities, entitySignalsRaw] = await Promise.all([
    getEvidenceForSignal(signal.observation_ids),
    Promise.all(signal.entity_ids.map((id) => getEntityById(id))),
    firstEntityId ? getSignalsByEntity(firstEntityId) : Promise.resolve([]),
  ])
  const entityNames = entities.filter((e): e is NonNullable<typeof e> => e !== null)
  const relatedByEntity = entitySignalsRaw.filter((s) => s.id !== signal.id).slice(0, 5)

  const EVIDENCE_TIER_LABEL: Record<string, string> = {
    UNASSESSED: 'Not yet assessed',
    PRIMARY_CONFIRMED: 'Single primary source',
    CORROBORATED: 'Corroborated by multiple sources',
    VERIFIED: 'Independently verified',
  }

  return (
    <>
      <div className="textured-bg relative px-6 pb-24 pt-40">
        <div className="tech-grid" />
        <div className="relative z-10 mx-auto max-w-4xl">
          <nav className="font-caption mb-6 text-silver-haze" aria-label="Breadcrumb">
            <Link href="/signals" className="hover:text-mint-signal">
              Signals
            </Link>
            <span className="mx-2">›</span>
            <span>{formatCategory(signal.category)}</span>
          </nav>

          <div className="mb-8 overflow-hidden border border-border-subtle">
            <SignalIllustration
              category={signal.category}
              title={signal.title}
              className="h-auto w-full"
            />
          </div>

          <header className="mb-8 border-b border-border-subtle pb-8">
            <div className="mb-4 flex flex-wrap items-center gap-2">
              <span className="pill bg-mint-signal px-3 py-1 text-xs font-medium text-deep-obsidian">
                {signal.status}
              </span>
              <span className="pill border border-border-subtle px-3 py-1 text-xs text-silver-haze">
                {formatCategory(signal.category)}
              </span>
              <span className="pill border border-border-subtle px-3 py-1 text-xs text-silver-haze">
                CONFIDENCE {signal.confidence_score}%
              </span>
            </div>
            <h1 className="font-heading mb-4 text-3xl text-frost md:text-4xl">{signal.title}</h1>
            <div className="font-caption flex flex-wrap items-center gap-4 text-silver-haze">
              <time dateTime={signal.created_at}>
                Detected {formatRelativeTime(signal.created_at)}
              </time>
              <span>·</span>
              <span>{formatDate(signal.created_at)}</span>
              <span>·</span>
              <span>SIGNAL {signal.id.slice(0, 8).toUpperCase()}</span>
            </div>
          </header>

          <div className="grid gap-8 md:grid-cols-[1fr_240px]">
            <div className="space-y-6">
              <section>
                <h2 className="font-caption mb-3 text-silver-haze">SIGNAL ANALYSIS</h2>
                <p className="text-lg leading-relaxed text-silver-haze">{signal.description}</p>
              </section>

              {evidence.length > 0 && (
                <section className="border-t border-border-subtle pt-6">
                  <h2 className="font-caption mb-4 text-silver-haze">EVIDENCE</h2>
                  <div className="space-y-4">
                    {evidence.map((e) => (
                      <div key={e.url} className="border border-border-subtle bg-surface-tonal p-4">
                        <div className="mb-2 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-silver-haze">
                          <span className="text-frost">{e.sourceName}</span>
                          <span className="uppercase">{e.sourceType}</span>
                          {e.publishedAt && <span>{formatDate(e.publishedAt)}</span>}
                        </div>
                        {e.excerpt && (
                          <p className="mb-3 text-sm italic leading-relaxed text-silver-haze">
                            &ldquo;{e.excerpt}
                            {e.excerpt.length >= 240 ? '…' : ''}&rdquo;
                          </p>
                        )}
                        <a
                          href={e.url}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-xs text-silver-haze underline decoration-border-subtle underline-offset-2 hover:text-mint-signal"
                        >
                          Read the source →
                        </a>
                      </div>
                    ))}
                  </div>
                </section>
              )}

              {relatedEvents.length > 0 && (
                <section className="border-t border-border-subtle pt-6">
                  <h2 className="font-caption mb-4 text-silver-haze">
                    RELATED EVENTS ({relatedEvents.length})
                  </h2>
                  <div className="space-y-3">
                    {relatedEvents.map((event) => (
                      <Link
                        key={event.id}
                        href={`/events/${event.id}`}
                        className="block border border-border-subtle bg-surface-tonal p-4 transition-colors hover:border-mint-signal"
                      >
                        <p className="font-caption mb-1 text-silver-haze">
                          {event.event_type.replace('_', ' ')}
                        </p>
                        <p className="text-frost">{event.title}</p>
                      </Link>
                    ))}
                  </div>
                </section>
              )}

              <section className="border border-border-subtle bg-surface-tonal p-4">
                <h2 className="font-caption mb-3 text-silver-haze">SIGNAL STATUS</h2>
                <div className="grid grid-cols-2 gap-3 text-xs sm:grid-cols-3">
                  <StatusItem label="Status" value={signal.status} />
                  <StatusItem label="Category" value={formatCategory(signal.category)} />
                  <StatusItem
                    label="Evidence"
                    value={EVIDENCE_TIER_LABEL[signal.evidence_tier] ?? signal.evidence_tier}
                  />
                  <StatusItem
                    label="Entity"
                    value={
                      entityNames.length > 0
                        ? entityNames.map((e) => e.name).join(', ')
                        : 'None detected'
                    }
                  />
                  <StatusItem
                    label="Decision"
                    value={
                      signal.manual_override
                        ? 'Manual editorial override'
                        : 'Automated · no editorial override'
                    }
                  />
                  <StatusItem
                    label="Last observed"
                    value={
                      signal.momentum_last_calculated
                        ? formatRelativeTime(signal.momentum_last_calculated)
                        : 'Pending'
                    }
                  />
                </div>
              </section>

              {relatedByEntity.length > 0 && (
                <section className="border-t border-border-subtle pt-6">
                  <h2 className="font-caption mb-4 text-silver-haze">
                    RELATED SIGNALS ({relatedByEntity.length})
                  </h2>
                  <div className="space-y-3">
                    {relatedByEntity.map((related) => (
                      <Link
                        key={related.id}
                        href={`/signals/${related.id}`}
                        className="block border border-border-subtle bg-surface-tonal p-4 transition-colors hover:border-mint-signal"
                      >
                        <p className="font-caption mb-1 text-silver-haze">
                          {formatCategory(related.category)}
                        </p>
                        <p className="text-frost">{related.title}</p>
                      </Link>
                    ))}
                  </div>
                </section>
              )}
            </div>

            <aside className="space-y-6">
              <section className="border border-border-subtle bg-surface-tonal p-4">
                <h2 className="font-caption mb-4 text-silver-haze">SIGNAL SCORES</h2>
                <div className="space-y-2.5">
                  <VfinalScoreBar value={signal.signal_score} label="Signal" />
                  <VfinalScoreBar value={signal.confidence_score} label="Conf" />
                  <VfinalScoreBar value={signal.momentum_score} label="Momentum" />
                </div>
              </section>

              <section className="border border-border-subtle bg-surface-tonal p-4">
                <h2 className="font-caption mb-4 text-silver-haze">FACTOR BREAKDOWN</h2>
                <div className="space-y-2">
                  <VfinalScoreBar value={signal.impact_factor * 10} label="Impact" />
                  <VfinalScoreBar value={signal.actor_factor * 10} label="Actor" />
                  <VfinalScoreBar value={signal.novelty_factor * 10} label="Novelty" />
                  <VfinalScoreBar value={signal.verifiability_factor * 10} label="Verify" />
                  <VfinalScoreBar value={signal.strategic_factor * 10} label="Strategic" />
                </div>
              </section>

              <Link
                href="/signals"
                className="font-caption block text-center text-silver-haze transition-colors hover:text-mint-signal"
              >
                ← ALL SIGNALS
              </Link>
            </aside>
          </div>
        </div>
      </div>
    </>
  )
}

function StatusItem({ label, value }: { label: string; value: string }): React.JSX.Element {
  return (
    <div>
      <p className="font-caption mb-0.5 text-silver-haze">{label.toUpperCase()}</p>
      <p className="text-frost">{value}</p>
    </div>
  )
}

function VfinalScoreBar({ value, label }: { value: number; label: string }): React.JSX.Element {
  const clamped = Math.max(0, Math.min(100, value))
  return (
    <div className="flex items-center gap-2">
      {/* REAL BUG FIXED (explicit owner instruction, screenshot-
          annotated, 2026-09-05): "Momentum" and "Strategic" visibly
          overflowed the fixed w-16 (64px) label column, colliding
          with the score bar next to them. Confirmed via real,
          measured pixel widths in a live browser (not guessed): at
          this real font-caption size/weight, "Momentum" needs 87px
          and "Strategic" needs 78px -- both genuinely exceed 64px.
          Widened to w-24 (96px), confirmed via the same live
          measurement to comfortably fit every real label currently
          used on this page (Signal, Conf, Momentum, Impact, Actor,
          Novelty, Verify, Strategic). */}
      <span className="font-caption w-24 shrink-0 text-silver-haze">{label}</span>
      <div className="h-1.5 flex-1 bg-border-subtle">
        <div className="h-full bg-mint-signal" style={{ width: `${clamped}%` }} />
      </div>
      <span className="w-8 shrink-0 text-right font-mono text-xs text-frost">
        {Math.round(clamped)}
      </span>
    </div>
  )
}
