import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { VfinalPublicShell } from '@/components/layout/vfinal-public-shell'
import { SignalIllustration } from '@/components/signals/signal-illustration'
import { getSignalById } from '@/modules/signals/queries'
import { getEventsBySignal } from '@/modules/events/queries'
import { getSourceLinksForSignal } from '@/modules/observations/queries'
import { SourceFaviconStrip } from '@/components/signals/source-favicon-strip'
import { formatDate, formatRelativeTime, formatCategory } from '@/lib/utils/format'

export const dynamic = 'force-dynamic'

interface SignalPageProps {
  params: Promise<{ slug: string }>
}

// Pre-generate paths for known signals at build time
export async function generateStaticParams(): Promise<{ slug: string }[]> {
  return []
}

export async function generateMetadata({ params }: SignalPageProps): Promise<Metadata> {
  const { slug } = await params
  const signal = await getSignalById(slug)
  if (!signal) return { title: 'Signal Not Found' }
  return {
    title: signal.title,
    description: signal.description,
  }
}

/**
 * AIscentra — vfinal /signals/[slug] page (Frontend Design Foundation,
 * layer 5A)
 *
 * Visual language migrated to vfinal (VfinalPublicShell, mint-signal/
 * frost/silver-haze tokens, font-caption/font-heading classes); ALL
 * real functional logic UNCHANGED: getSignalById, getEventsBySignal,
 * getSourceLinksForSignal (same RLS-bound fetch ordering, same safety
 * boundary), SourceFaviconStrip, SignalIllustration (a real, native
 * SVG generated by this project's own illustration-style.ts -- not an
 * external/temporary image URL, so it stays as-is), notFound()
 * behavior, generateMetadata, generateStaticParams, dynamic rendering.
 * ScoreBar/badge components replaced with plain vfinal-styled bars/
 * pills showing the exact same real numeric values -- no data changed.
 */
export default async function SignalPage({ params }: SignalPageProps): Promise<React.JSX.Element> {
  const { slug } = await params
  const [signal, relatedEvents] = await Promise.all([getSignalById(slug), getEventsBySignal(slug)])

  const sourceLinks = signal ? await getSourceLinksForSignal(signal.observation_ids) : []

  if (!signal) notFound()

  return (
    <VfinalPublicShell>
      <div className="textured-bg relative px-6 pb-24 pt-40">
        <div className="tech-grid" />
        <div className="relative z-10 mx-auto max-w-4xl">
          <nav className="font-caption mb-6 text-silver-haze" aria-label="Breadcrumb">
            <Link href="/signals" className="hover:text-mint-signal">
              Signals
            </Link>
            <span className="mx-2">›</span>
            <span>{formatCategory(signal.category)}</span>
          </nav>

          <div className="mb-8 overflow-hidden border border-border-subtle">
            <SignalIllustration
              category={signal.category}
              title={signal.title}
              className="h-auto w-full"
            />
          </div>

          <header className="mb-8 border-b border-border-subtle pb-8">
            <div className="mb-4 flex flex-wrap items-center gap-2">
              <span className="pill bg-mint-signal px-3 py-1 text-xs font-medium text-deep-obsidian">
                {signal.status}
              </span>
              <span className="pill border border-border-subtle px-3 py-1 text-xs text-silver-haze">
                {formatCategory(signal.category)}
              </span>
              <span className="pill border border-border-subtle px-3 py-1 text-xs text-silver-haze">
                CONFIDENCE {signal.confidence_score}%
              </span>
            </div>
            <h1 className="font-heading mb-4 text-3xl text-frost md:text-4xl">{signal.title}</h1>
            <div className="font-caption flex flex-wrap items-center gap-4 text-silver-haze">
              <time dateTime={signal.created_at}>
                Detected {formatRelativeTime(signal.created_at)}
              </time>
              <span>·</span>
              <span>{formatDate(signal.created_at)}</span>
              <span>·</span>
              <span>SIGNAL {signal.id.slice(0, 8).toUpperCase()}</span>
            </div>
          </header>

          <div className="grid gap-8 md:grid-cols-[1fr_240px]">
            <div className="space-y-6">
              <section>
                <h2 className="font-caption mb-3 text-silver-haze">SIGNAL ANALYSIS</h2>
                <p className="text-lg leading-relaxed text-silver-haze">{signal.description}</p>
                {sourceLinks.length > 0 && (
                  <div className="mt-3">
                    <SourceFaviconStrip sources={sourceLinks} />
                  </div>
                )}
              </section>

              {relatedEvents.length > 0 && (
                <section className="border-t border-border-subtle pt-6">
                  <h2 className="font-caption mb-4 text-silver-haze">
                    RELATED EVENTS ({relatedEvents.length})
                  </h2>
                  <div className="space-y-3">
                    {relatedEvents.map((event) => (
                      <Link
                        key={event.id}
                        href={`/events/${event.id}`}
                        className="block border border-border-subtle bg-surface-tonal p-4 transition-colors hover:border-mint-signal"
                      >
                        <p className="font-caption mb-1 text-silver-haze">
                          {event.event_type.replace('_', ' ')}
                        </p>
                        <p className="text-frost">{event.title}</p>
                      </Link>
                    ))}
                  </div>
                </section>
              )}

              <section className="border border-border-subtle bg-surface-tonal p-4">
                <h2 className="font-caption mb-3 text-silver-haze">SIGNAL STATUS</h2>
                <div className="grid grid-cols-2 gap-3 text-xs sm:grid-cols-3">
                  <StatusItem label="Status" value={signal.status} />
                  <StatusItem label="Category" value={formatCategory(signal.category)} />
                  <StatusItem label="Sources" value={`${signal.observation_ids.length} linked`} />
                  <StatusItem label="Entities" value={`${signal.entity_ids.length} detected`} />
                  <StatusItem
                    label="Override"
                    value={signal.manual_override ? 'Manual' : 'Automated'}
                  />
                  <StatusItem
                    label="Momentum"
                    value={
                      signal.momentum_last_calculated
                        ? formatRelativeTime(signal.momentum_last_calculated)
                        : 'Pending'
                    }
                  />
                </div>
              </section>
            </div>

            <aside className="space-y-6">
              <section className="border border-border-subtle bg-surface-tonal p-4">
                <h2 className="font-caption mb-4 text-silver-haze">SIGNAL SCORES</h2>
                <div className="space-y-2.5">
                  <VfinalScoreBar value={signal.signal_score} label="Signal" />
                  <VfinalScoreBar value={signal.confidence_score} label="Conf" />
                  <VfinalScoreBar value={signal.momentum_score} label="Momentum" />
                </div>
              </section>

              <section className="border border-border-subtle bg-surface-tonal p-4">
                <h2 className="font-caption mb-4 text-silver-haze">FACTOR BREAKDOWN</h2>
                <div className="space-y-2">
                  <VfinalScoreBar value={signal.impact_factor * 10} label="Impact" />
                  <VfinalScoreBar value={signal.actor_factor * 10} label="Actor" />
                  <VfinalScoreBar value={signal.novelty_factor * 10} label="Novelty" />
                  <VfinalScoreBar value={signal.verifiability_factor * 10} label="Verify" />
                  <VfinalScoreBar value={signal.strategic_factor * 10} label="Strategic" />
                </div>
              </section>

              <Link
                href="/signals"
                className="font-caption block text-center text-silver-haze transition-colors hover:text-mint-signal"
              >
                ← ALL SIGNALS
              </Link>
            </aside>
          </div>
        </div>
      </div>
    </VfinalPublicShell>
  )
}

function StatusItem({ label, value }: { label: string; value: string }): React.JSX.Element {
  return (
    <div>
      <p className="font-caption mb-0.5 text-silver-haze">{label.toUpperCase()}</p>
      <p className="text-frost">{value}</p>
    </div>
  )
}

function VfinalScoreBar({ value, label }: { value: number; label: string }): React.JSX.Element {
  const clamped = Math.max(0, Math.min(100, value))
  return (
    <div className="flex items-center gap-2">
      <span className="font-caption w-16 shrink-0 text-silver-haze">{label}</span>
      <div className="h-1.5 flex-1 bg-border-subtle">
        <div className="h-full bg-mint-signal" style={{ width: `${clamped}%` }} />
      </div>
      <span className="w-8 shrink-0 text-right font-mono text-xs text-frost">
        {Math.round(clamped)}
      </span>
    </div>
  )
}
