import type { Signal } from '@/types/database'

export function makeSignal(overrides: Partial<Signal>): Signal {
  return {
    id: 'sig-5a',
    title: 'Layer 5A Test Signal',
    description: 'Test description.',
    category: 'MODELS',
    status: 'ACTIVE',
    impact_factor: 5,
    actor_factor: 5,
    novelty_factor: 5,
    verifiability_factor: 5,
    strategic_factor: 5,
    authority_factor: 5,
    corroboration_factor: 5,
    specificity_factor: 5,
    category_confidence_factor: 5,
    consistency_factor: 5,
    signal_score: 65,
    confidence_score: 70,
    momentum_score: 40,
    intelligence_type: 'SIGNAL',
    qualification_score: 65,
    qualification_detail: {},
    sis_novelty: 5,
    sis_importance: 5,
    sis_urgency: 5,
    sis_confidence: 5,
    sis_final: 65,
    relevance_horizon: 'MONTHS',
    relevance_detail: {},
    anti_hype_score: 5,
    anti_hype_flags: {},
    human_relevance_flags: {},
    lifecycle_state: 'ACTIVE',
    dormant_reason: null,
    reactivate_after: null,
    quality_state: 'APPROVED',
    quality_reason_codes: [],
    quality_rule_version: 'quality-foundation-v1',
    quality_evaluated_at: new Date().toISOString(),
    quarantined_at: null,
    evidence_tier: 'PRIMARY_CONFIRMED',
    validation_flags: [],
    manual_override: false,
    expiration_reason: null,
    expired_at: null,
    observation_ids: [],
    entity_ids: [],
    metadata: {},
    engine_version: 'v2',
    momentum_last_calculated: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    ...overrides,
  } as Signal
}
