/**
 * AIscentra — Inline Signal Illustration
 *
 * Renders the SAME abstract, category-based motif system as
 * src/app/signals/[slug]/opengraph-image.tsx, but as native SVG for
 * direct in-page display (every visitor sees this on the signal page
 * itself, not just link-preview consumers). Reuses the shared, pure
 * src/modules/signals/illustration-style.ts logic (motifForCategory,
 * extractKeyword, ILLUSTRATION_PALETTE) so both surfaces stay visually
 * consistent from one source of truth.
 *
 * Free and unique by construction: pure SVG generated by this
 * project's own code, zero external API calls, zero per-render cost,
 * and a motif/palette system that exists nowhere else -- not a
 * template, not a generic icon library.
 */
import {
  motifForCategory,
  extractKeyword,
  ILLUSTRATION_PALETTE,
} from '@/modules/signals/illustration-style'
import type { IllustrationMotif } from '@/modules/signals/illustration-style'
import type { SignalCategory } from '@/types/database'

const P = ILLUSTRATION_PALETTE
const WIDTH = 1200
const HEIGHT = 200

function MotifShapes({ motif }: { motif: IllustrationMotif }): React.JSX.Element {
  const cx = WIDTH / 2
  const cy = HEIGHT / 2

  switch (motif) {
    case 'CONCENTRIC_RINGS':
      return (
        <>
          <circle
            cx={cx}
            cy={cy}
            r={90}
            fill="none"
            stroke={P.textMuted}
            strokeWidth={1.5}
            opacity={0.6}
          />
          <circle
            cx={cx}
            cy={cy}
            r={60}
            fill="none"
            stroke={P.textMuted}
            strokeWidth={1.5}
            opacity={0.4}
          />
          <circle
            cx={cx}
            cy={cy}
            r={30}
            fill="none"
            stroke={P.textMuted}
            strokeWidth={1.5}
            opacity={0.25}
          />
        </>
      )

    case 'LAYERED_BARS':
      return (
        <>
          {[0, 1, 2, 3, 4].map((i) => (
            <rect
              key={i}
              x={200}
              y={60 + i * 18}
              width={280 - i * 20}
              height={8}
              fill={P.textMuted}
              opacity={0.3 + i * 0.12}
            />
          ))}
        </>
      )

    case 'OVERLAPPING_SQUARES':
      return (
        <>
          <rect
            x={cx - 80}
            y={40}
            width={110}
            height={110}
            fill="none"
            stroke={P.textMuted}
            strokeWidth={1.5}
            opacity={0.3}
          />
          <rect
            x={cx - 40}
            y={70}
            width={110}
            height={110}
            fill="none"
            stroke={P.textMuted}
            strokeWidth={1.5}
            opacity={0.45}
          />
          <rect
            x={cx}
            y={100}
            width={110}
            height={90}
            fill="none"
            stroke={P.textMuted}
            strokeWidth={1.5}
            opacity={0.6}
          />
        </>
      )

    case 'LATTICE_GRID':
      return (
        <>
          {Array.from({ length: 4 }).map((_, row) =>
            Array.from({ length: 8 }).map((__, col) => (
              <rect
                key={`${row}-${col}`}
                x={180 + col * 55}
                y={30 + row * 40}
                width={28}
                height={28}
                fill="none"
                stroke={P.textMuted}
                strokeWidth={1}
                opacity={0.25}
              />
            )),
          )}
        </>
      )

    case 'BRANCHING_LINES':
      return (
        <>
          {[-30, -15, 0, 15, 30].map((deg) => (
            <line
              key={deg}
              x1={cx}
              y1={cy}
              x2={cx + 120 * Math.sin((deg * Math.PI) / 180)}
              y2={cy - 90 * Math.cos((deg * Math.PI) / 180)}
              stroke={P.textMuted}
              strokeWidth={1.5}
              opacity={0.4}
            />
          ))}
        </>
      )

    case 'ASCENDING_BARS':
      return (
        <>
          {[30, 50, 65, 85, 105].map((h, i) => (
            <rect
              key={i}
              x={220 + i * 45}
              y={HEIGHT - 40 - h}
              width={26}
              height={h}
              fill={P.textMuted}
              opacity={0.3 + i * 0.12}
            />
          ))}
        </>
      )

    case 'PARALLEL_LINES':
      return (
        <>
          {[0, 1, 2, 3, 4].map((i) => (
            <line
              key={i}
              x1={200}
              y1={50 + i * 24}
              x2={520}
              y2={50 + i * 24}
              stroke={P.textMuted}
              strokeWidth={1.5}
              opacity={0.25 + i * 0.08}
            />
          ))}
        </>
      )

    case 'CONNECTED_NODES': {
      const nodes: Array<[number, number]> = [
        [220, 90],
        [320, 55],
        [420, 100],
        [300, 140],
        [400, 150],
      ]
      return (
        <>
          <line
            x1={220}
            y1={90}
            x2={320}
            y2={55}
            stroke={P.textMuted}
            strokeWidth={1}
            opacity={0.25}
          />
          <line
            x1={320}
            y1={55}
            x2={420}
            y2={100}
            stroke={P.textMuted}
            strokeWidth={1}
            opacity={0.25}
          />
          <line
            x1={220}
            y1={90}
            x2={300}
            y2={140}
            stroke={P.textMuted}
            strokeWidth={1}
            opacity={0.25}
          />
          <line
            x1={300}
            y1={140}
            x2={400}
            y2={150}
            stroke={P.textMuted}
            strokeWidth={1}
            opacity={0.25}
          />
          {nodes.map(([x, y], i) => (
            <circle key={i} cx={x} cy={y} r={6} fill={P.textMuted} opacity={0.6} />
          ))}
        </>
      )
    }

    case 'ANGULAR_BLOCKS':
    default:
      return (
        <>
          {[
            { x: 210, y: 60, w: 90, h: 45, deg: -8 },
            { x: 330, y: 90, w: 110, h: 50, deg: 6 },
            { x: 260, y: 120, w: 80, h: 40, deg: 12 },
          ].map((b, i) => (
            <rect
              key={i}
              x={b.x}
              y={b.y}
              width={b.w}
              height={b.h}
              fill="none"
              stroke={P.textMuted}
              strokeWidth={1.5}
              opacity={0.35 + i * 0.15}
              transform={`rotate(${b.deg} ${b.x + b.w / 2} ${b.y + b.h / 2})`}
            />
          ))}
        </>
      )
  }
}

export function SignalIllustration({
  category,
  title,
  className,
}: {
  category: SignalCategory
  title: string
  className?: string
}): React.JSX.Element {
  const motif = motifForCategory(category)
  const keyword = extractKeyword(title)

  return (
    <svg
      viewBox={`0 0 ${WIDTH} ${HEIGHT}`}
      className={className}
      role="img"
      aria-label={`Abstract illustration for ${category} signal: ${keyword}`}
    >
      <rect x={0} y={0} width={WIDTH} height={HEIGHT} fill={P.dark} />
      <MotifShapes motif={motif} />
      <text
        x={40}
        y={HEIGHT / 2 + 12}
        fontFamily="monospace"
        fontSize={44}
        fontWeight={300}
        fill={P.textPrimary}
      >
        {keyword}
      </text>
    </svg>
  )
}
