-- ============================================================
-- Migration: 20260728000009_create_signal_decision_log
-- Signal Engine V2 — Decision Log
-- Every published Signal stores WHY it became Signal vs Weak/Observation
-- ============================================================

CREATE TABLE IF NOT EXISTS public.signal_decision_log (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- ── Subject ───────────────────────────────────────────────────────────────
  signal_id           UUID REFERENCES public.signals(id),
  observation_id      UUID NOT NULL REFERENCES public.observations(id),

  -- ── Decision ──────────────────────────────────────────────────────────────
  decision            TEXT NOT NULL,  -- 'SIGNAL'|'WEAK_SIGNAL'|'DISCARD'|'ARCHIVE'
  previous_decision   TEXT,           -- if this is a re-evaluation or promotion

  -- ── Qualification breakdown ───────────────────────────────────────────────
  qualification_score     NUMERIC(5,2),
  qualification_breakdown JSONB NOT NULL DEFAULT '{}',
  -- {
  --   "changes_technology":    {"score": 8.0, "weight": 0.20, "weighted": 1.60, "reason": "..."},
  --   "changes_engineering":   {"score": 6.0, "weight": 0.15, "weighted": 0.90, "reason": "..."},
  --   "changes_adoption":      {"score": 4.0, "weight": 0.15, "weighted": 0.60, "reason": "..."},
  --   "changes_investment":    {"score": 3.0, "weight": 0.10, "weighted": 0.30, "reason": "..."},
  --   "changes_science":       {"score": 7.0, "weight": 0.10, "weighted": 0.70, "reason": "..."},
  --   "competitive_advantage": {"score": 5.0, "weight": 0.10, "weighted": 0.50, "reason": "..."},
  --   "invalidates_prior":     {"score": 2.0, "weight": 0.10, "weighted": 0.20, "reason": "..."},
  --   "changes_regulation":    {"score": 1.0, "weight": 0.05, "weighted": 0.05, "reason": "..."},
  --   "changes_infrastructure":{"score": 2.0, "weight": 0.05, "weighted": 0.10, "reason": "..."},
  --   "total": 4.95
  -- }

  -- ── Strategic Importance Score ────────────────────────────────────────────
  sis_novelty     NUMERIC(4,2),
  sis_importance  NUMERIC(4,2),
  sis_urgency     NUMERIC(4,2),
  sis_confidence  NUMERIC(4,2),
  sis_final       NUMERIC(4,2),

  -- ── Human relevance breakdown ─────────────────────────────────────────────
  human_relevance_breakdown JSONB NOT NULL DEFAULT '{}',
  -- {
  --   "cto":                  true,
  --   "research_director":    true,
  --   "vc":                   false,
  --   "founder":              true,
  --   "government_analyst":   false,
  --   "enterprise_architect": false,
  --   "roles_yes_count":      3
  -- }

  -- ── Reality check ─────────────────────────────────────────────────────────
  anti_hype_score NUMERIC(4,2),
  anti_hype_flags JSONB DEFAULT '{}',

  -- ── Rejection ─────────────────────────────────────────────────────────────
  rejection_code   TEXT,   -- R-01 through R-12
  rejection_reason TEXT,
  promotion_from   TEXT,   -- if promoted from WEAK_SIGNAL

  -- ── Engine Justification (Improvement 4) ──────────────────────────────────
  -- Narrative explanation of why the engine made this specific decision.
  -- Not a template. Generated by the engine as part of Signal creation.
  -- Example: "Qualified as SIGNAL rather than WEAK_SIGNAL because sis_importance=8.5
  --   (new runtime layer for embodied agents addresses a gap no existing system fills)
  --   and 4 of 6 professional roles would act on this. Anti-hype score 7.0 reflects
  --   institutional arXiv source with reproducible results."
  engine_justification TEXT,

  -- ── Threshold snapshot ────────────────────────────────────────────────────
  -- Records thresholds in effect at decision time for retrospective analysis
  thresholds_snapshot JSONB NOT NULL DEFAULT '{}',
  -- {
  --   "qualification_signal_min": 6.0,
  --   "qualification_weak_min":   3.0,
  --   "sis_signal_min":           6.0,
  --   "sis_weak_min":             4.0,
  --   "human_relevance_min":      3,
  --   "engine_version":           "v2.0"
  -- }

  -- ── Engine versioning ─────────────────────────────────────────────────────
  engine_version  TEXT NOT NULL DEFAULT 'v2.0',

  decided_at      TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_dl_signal      ON public.signal_decision_log(signal_id);
CREATE INDEX IF NOT EXISTS idx_dl_observation ON public.signal_decision_log(observation_id);
CREATE INDEX IF NOT EXISTS idx_dl_decision    ON public.signal_decision_log(decision);
CREATE INDEX IF NOT EXISTS idx_dl_version     ON public.signal_decision_log(engine_version);

-- RLS — decision log is internal
ALTER TABLE public.signal_decision_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role only"
  ON public.signal_decision_log FOR ALL
  TO service_role
  USING (true);

COMMENT ON TABLE public.signal_decision_log IS
  'Decision Log for Signal Engine V2.
   Every Signal, Weak Signal, and Discard stores complete reasoning.
   engine_justification = narrative explanation of the specific decision.
   thresholds_snapshot = what thresholds were active at decision time.
   Enables retrospective analysis: how would changing thresholds affect past decisions?';
